language: scala
jdk:
  - openjdk8
sudo: required
services:
  - docker
env:
  global:
    - secure: kImcdca6c/QzoNm3t5VNAYmcXSTIjonmHuGxfN7zpHbKdKIaGfde+PAqAb3A1vXknpZ+vDnzb1D4KhzNbrfR772GkTm6dnzX77G+3VCWI6Y5pCHwIuNBEtJYIvxuI15d7OMNFTALA/SfiBBQPqUDwOlhDemUSDDZASTxhmln04XeqhklbhAQ16dxY8gqSW1C8SYJIbILwAm4vu9a7b49nVtUImWUiaeVvpml33URpwO51j1lWNt3SgAFaW5pv9AE2Bjr/vMF16PrDY3HvHAz8tzT4QUnrqKwVEism+gPIDEHYzO+7Ne0Ri+eYwI0x6lGMVhHeptOm0OwwPH2WIeTSfDIVoW6S/rlJUAUy6242J1MB88h3ybtDfsCfiGJ8il2kI2rQIHoBUbIcKs/+NHTi+knlmzx4Vqe05sUYMfhx/Hu5MqGnrHwW2Aw+kLrwyaalEtU566opnXxpcSUynPIr43n3nWwSVIdtOZYI+Z3SFQdLUyCuwkmb6xVV8ncMYYmCtQaodB2/N2joXj4Mc1pu0J2eU3r4UpgVgtv4rvc5zV24liVC49F3VcbAYOJtES4HXKr3TkNnqNuAkdX3Rwh3Q+yx3Xz91jayZUzDZJBGzCO/QiBkZ+4IwL80dqEBnen+vyS1jNAI7qwmQbp7MW5tEyN097zTZxrrVHiKUfTc8o=
    - secure: uxahN3sarWezGTOMtgdOO3Z8Ghf3Z9VCKy1+tJJ+hx3wFfg1u1N9APIwYeOL4oKlnkAzt0AfdPVp1ZAcGLDpwjK3xFvE/gty70CrKzhvhH8a1pArblvN8auwajAf8trW6bEMPMNEAdOxDjRoqa2hFPGR6M7WBRRAZnD/hnj1B3RhLtGRIdUY8r/l79TVkzNbxZO/T8AnH+9Lh3c+Hz0Ix0sYiCxo8D98oiFl2LuJiZfaMlepGdaaz+R8R9XS3oYW346sPvLdVma0voRWcNefO2QFrbmOTddrUTdJ3bkfqob3wwM5BvgOXIhh5ZL5iFTU4bhePxl+BJNV+mb2YYWxYfa1OnUkTZdveHOgRevZTTxUCGc0kcSPFTfziXjq3ognZ2vnVBVnKKpggxzveFKOEXcFxKOSxs8dUSPHlQ8ZMikV64DzTP0cwQYX0a0zRm2L51jcctM/v9DM1msDwdNSk5GWrKkjK4Atyg4RsWDVLEiuUVGs4cP9K3hcKYfcnAOIOtQQmq4Sw26VWvJK6vYWc3CsKl0ZJXOzlSgwIFyoITD5rBlVIZY855Ckz3j9IWSJVvgSv7zMHB49ODVq+l4M+XNXSbdsMDmxbqjk01CSPHd7CWpb6OwEJw8tuHd/nBsj8tzaHpDlxp61FFPq2MzKjf8u75ao+v86oDxtenc5i/M=
    - secure: BCU14UKhyeUCWCVcF6SuidH3SeZzU1jkfAtyrx8roWpTwaMD5zrBF1zlWJHtYcDBq/b1MpdXGYY+Mq30KtBaobXKDkU/B+MHJCvN1eHHBO7NxNw+/U5IICs/2IV/jC9ANMevMO4pGQbx15DiZcGGk0uIyZiWtX7u8cGcM+i6ldLAdPoVl/8Wj2KUH9y5ZvCGn5BJBA+UJbum/watf7t6bYvlnFcesJ5ahL4TvwLMksTqp20vc7YUmO5FnnoXt4HZFhMjbr5i35MLTXoM4Z1TYbdfod0tnIs3pf2A5up+X/wOxTnmW8+p7iLeu1GsQLAtsPPXiIYqdA8TBJ7jwHPsdIbfFYyJT4lzeaXqOs5gf7LhbzU1ehMuLo7K8p9yfXiXoYW62bBJy0KCeEvBYeCrylI7Y/x9uauuowCIie/iknLC5xI0dO5Off7ModOvpXRuj0pWS8hEEXH0eTqaNPnl7LSIp5C6kTQ2HNHUaCNWAYXx9Wf1kWJOu6k4eQVEBdg5NnMDuB2fRWCqFVSLd1MEHFnbd/Ll4SnIDo7DMk6NLPZ+aIDtYyMtvtRrg6b1P8wOGwkzxMTMtPFFdYFWEuni4IBF0wmTye781v0DQzTAmvT2WNIxwjb6kljHjlBHouVdmcKUeVSN9VQ4+D0G00Ti0SFqSp+K1wlgLNm7YuN8tvU=
    - secure: O+QOjGKLJgCPfeQ+LGBc5JvdqsfbSRig2d6Hx5RRU9yutcYqtj+QwKqS7f4d14m5Ob9nppV7GDWTlJdgCMYyRDkpo+kSk//05t2JdwnbXcL44Wozq9O3g5ETS9mC9aPDt1BpoPXJr6P6woInBH09ysWzsk4Jt275w1CJOytZrSlnY1biTtpRexQmWp/2Zr/JEV5MdeYiX0U++/UeOwdct7IxIzz8Up3Q9NzCQaB1zxMY5RgoJebQHAjZmqCissBjGR8z26St5sgyfa4tHHBB4MaKJgdDyGg/MtnJMCmhWwEIOLU5v73r3Jnil2cvDKJAbvM1u6zAozO2i1U1UNRPX9UaWjh8ooTV3vZo+kREfUB37fWHSWcbObNKBWn7rZfhDvFR7o2zch0hqoFdJOgpuTJlJCVPr+X+YwBa+qInG/8QWyU5AIKJL/qMlNifOqTsXNqUBLe+tMNEa49u/VfR/Ybp9l3spSTdXNV56aPBWZOQjODeK6OnWCW9sYp1F387ALB1rCmcNfvDjH8wGcwZhxuFt5vdygeBIEAWDRj0XhDNa0s+rY/FFUDqf+GjAvyH6mP5o78pzGzh+YYlH8dWA/+y3+M26kq/4JpebPXC8vKqnfcrcrs+im9ALcXUm7aJG+UfpV+YS5rcJ1RRA+NrCUL0FINMd4asSpzsfbwwSvQ=
stages:
  - name: test
  - name: publish-and-deploy
    if: branch = master AND type = push
  - name: test-deployment
    if: branch = master AND type = push
  - name: release
    if: branch = master AND type = push
jobs:
  include:
    - stage: test
      script: |
        pip install --user cfn-lint && export PATH=$PATH:$HOME/.local/bin &&
        cfn-lint --template cfn-templates/*.yaml  --region eu-west-1 &&
        shellcheck **/*.sh &&
        ./cd-scripts/test-units.sh &&
        bash <(curl -s https://codecov.io/bash)
    - stage: test
      script: |
        ./cd-scripts/test-component.sh
    - stage: publish-and-deploy
        # So sbt-dynver derives the version correctly
      script: |
        git fetch --unshallow &&
        pip install --user awscli && export PATH=$PATH:$HOME/.local/bin &&
        ./cd-scripts/publish.sh eu-west-1 prod-green &&
        ./cd-scripts/deploy-service.sh eu-west-1 prod-green prod-green
    - stage: test-deployment
      script: |
        pip install --user awscli && export PATH=$PATH:$HOME/.local/bin &&
        ./cd-scripts/test-deployment.sh eu-west-1 api prod-green
    - stage: release
      script: |
        # So sbt-dynver derives the version correctly
        git fetch --unshallow &&
        ./cd-scripts/release.sh
cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2/cache
    - $HOME/.coursier
