AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Subdomain:
    Type: String
  NetworkStack:
    Type: String
Resources:
  RecordSetGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: "liquidityapp.com."
      RecordSets:
        - AliasTarget:
            HostedZoneId:
              Fn::ImportValue: !Sub "${NetworkStack}-NLBCanonicalHostedZoneID"
            DNSName:
              Fn::ImportValue: !Sub "${NetworkStack}-NLBDNSName"
          Name: !Sub "${Subdomain}.liquidityapp.com"
          Type: A
