AWSTemplateFormatVersion: '2010-09-09'
Resources:
  IAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub "liquidity-grafana-${AWS::Region}"
      Policies:
        - PolicyName: "liquidity-grafana"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudwatch:GetMetricStatistics
                  - cloudwatch:ListMetrics
                Resource:
                  - "*"
