version: '3'
services:
  mysql:
    image: "mysql:8.0"
    ports:
     - "3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    command: [
      "--character-set-client-handshake=false"
    ]
  zone-host:
    image: "liquidity:${TAG}"
    ports:
     - "8080"
    environment:
      JAVA_OPTS: "-Dakka.remote.artery.canonical.hostname=zone-host
        -Dakka.management.http.hostname=zone-host
        -Dakka.discovery.method=config
        -Dakka.discovery.config.services.liquidity.endpoints.0.host=zone-host
        -Dakka.discovery.config.services.liquidity.endpoints.1.host=client-relay
        -Dakka.discovery.config.services.liquidity.endpoints.2.host=analytics
        -Dakka.management.cluster.bootstrap.contact-point-discovery.\
         required-contact-point-nr=3
        -Dakka.cluster.roles.0=zone-host"
      MYSQL_HOSTNAME: "mysql"
      MYSQL_USERNAME: "root"
      MYSQL_PASSWORD: ""
  client-relay:
    image: "liquidity:${TAG}"
    ports:
     - "8080"
    environment:
      JAVA_OPTS: "-Dakka.remote.artery.canonical.hostname=client-relay
        -Dakka.management.http.hostname=client-relay
        -Dakka.discovery.method=config
        -Dakka.discovery.config.services.liquidity.endpoints.0.host=zone-host
        -Dakka.discovery.config.services.liquidity.endpoints.1.host=client-relay
        -Dakka.discovery.config.services.liquidity.endpoints.2.host=analytics
        -Dakka.management.cluster.bootstrap.contact-point-discovery.\
         required-contact-point-nr=3
        -Dakka.cluster.roles.0=client-relay
        -Dakka.http.server.remote-address-header=on"
      MYSQL_HOSTNAME: "mysql"
      MYSQL_USERNAME: "root"
      MYSQL_PASSWORD: ""
  analytics:
    image: "liquidity:${TAG}"
    ports:
     - "8080"
    environment:
      JAVA_OPTS: "-Dakka.remote.artery.canonical.hostname=analytics
        -Dakka.management.http.hostname=analytics
        -Dakka.discovery.method=config
        -Dakka.discovery.config.services.liquidity.endpoints.0.host=zone-host
        -Dakka.discovery.config.services.liquidity.endpoints.1.host=client-relay
        -Dakka.discovery.config.services.liquidity.endpoints.2.host=analytics
        -Dakka.management.cluster.bootstrap.contact-point-discovery.\
         required-contact-point-nr=3
        -Dakka.cluster.roles.0=analytics"
      MYSQL_HOSTNAME: "mysql"
      MYSQL_USERNAME: "root"
      MYSQL_PASSWORD: ""
